### PR TITLE
Wrap access to preference in try/catch

### LINKED ISSUE #11: Seeing what got precompiled vs Preferences error
While following the documentation under ["Seeing what got precompiled"](https://julialang.github.io/PrecompileTools.jl/stable/#Seeing-what-got-precompiled) I ran into an error.

```julia
julia> using PrecompileTools

julia> PrecompileTools.verbose[] = true
true

julia> include("src/LanguageServer.jl")
ERROR: LoadError: ArgumentError: Module Main.LanguageServer does not correspond to a loaded package!
Stacktrace:
 [1] get_uuid(m::Module)
   @ Preferences ~/.julia/packages/Preferences/VmJXL/src/utils.jl:8
 [2] var"@load_preference"(__source__::LineNumberNode, __module__::Module, key::Any, default::Any)
   @ Preferences ~/.julia/packages/Preferences/VmJXL/src/Preferences.jl:45
 [3] include(fname::String)
   @ Base.MainInclude ./client.jl:478
 [4] top-level scope
   @ REPL[3]:1
in expression starting at /home/mkitti/.julia/packages/PrecompileTools/NxtJ8/src/PrecompileTools.jl:115
in expression starting at /home/mkitti/.julia/dev/LanguageServer/src/LanguageServer.jl:1
```

### PR DESCRIPTION
**Pull request by timholy**
Fixes #11

### CODE REVIEW

**Comment by timholy** [comment]
@maleadt, how easy/hard (and resource-intensive) is it to do PkgEval on this? Would it be limited to just those packages depending on PrecompileTools?

If it's a crazy use of resources, I think this is fairly safe.

**Comment by aviatesk** [comment]
Thanks for this fix!

**Comment by timholy** [comment]
@maleadt, now I see from the docs that this will only test the direct dependents (very nice!), so I think it's worth running. Can you enable this repo?

**Comment by aviatesk** [comment]
What do you think on https://github.com/JuliaPackaging/Preferences.jl/pull/51?
With the change, we can do something like:
```julia
julia> using PrecompileTools

julia> PrecompileTools.verbose[] = true

julia> using Preferences, Pkg

julia> Preferences.uuid_cache[Main] =
           Pkg.project().dependencies["XXX"]

julia> include("src/XXX.jl") # see what gets precompiled with the configurations for XXX.jl
```

**Comment by timholy** [comment]
@nanosoldier `runtests()`

**Comment by timholy** [comment]
@nanosoldier `runtests(vs = "main")`

**Comment by nanosoldier** [comment]
Your job submission was not accepted: invalid argument to `vs` keyword.

**Comment by timholy** [comment]
@nanosoldier `runtests(vs = ":main")`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaLang/PrecompileTools.jl@d1c3641 vs. JuliaLang/PrecompileTools.jl@7242f78: Accepted

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaLang/PrecompileTools.jl@d1c3641 vs. JuliaLang/PrecompileTools.jl@7242f78: Running

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/PrecompileTools.jl/pull/13#issuecomment-1525717270) has completed - no new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/d1c3641_vs_7242f78/report.html).

**Pull request merged**
