### PR TITLE
Improve hygiene

### PR DESCRIPTION
**Pull request by timholy**
Closes #23

### CODE REVIEW

**Review by KristofferC — APPROVED** [review]

**Comment by timholy** [comment]
Shoot, I meant to do this:

@nanosoldier `runtests(vs = "@b4debd8cf0d94a89bbb08ab07f755623e8b58103")`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaLang/PrecompileTools.jl@ca9c1d0 vs. JuliaLang/PrecompileTools.jl@b4debd8: Accepted

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaLang/PrecompileTools.jl@ca9c1d0 vs. JuliaLang/PrecompileTools.jl@b4debd8: Running

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/PrecompileTools.jl/pull/24#issuecomment-1572622724) has completed - possible new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/ca9c1d0_vs_b4debd8/report.html).

**Comment by timholy** [comment]
@nanosoldier `runtests(["DFTK", "Zygote"], vs = "@b4debd8cf0d94a89bbb08ab07f755623e8b58103")`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob JuliaLang/PrecompileTools.jl@ca9c1d0 vs. JuliaLang/PrecompileTools.jl@b4debd8: Accepted

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/JuliaLang/PrecompileTools.jl/pull/24#issuecomment-1573326542) has completed - no new issues were detected.
A full report can be found [here](https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/by_hash/ca9c1d0_vs_b4debd8/report.html).

**Pull request merged**
